version = "1.0.0"
hardware_targets = ["rp2350", "bcm2712"]

[[ports]]
name = "cipher_in"
direction = "input"
content_type = "OctetStream"

[[ports]]
name = "clear_in"
direction = "input"
content_type = "OctetStream"

[[ports]]
name = "cipher_out"
direction = "output"
content_type = "OctetStream"

[[ports]]
name = "clear_out"
direction = "output"
content_type = "OctetStream"

[[resources]]
device_class = "system"
access = "write"
