//! The kernel's single capacity seam onto per-silicon compile-time constants.
//!
//! A no_std kernel sizes its static arenas at compile time, and the sizes are
//! silicon-specific (rp2040's 264 KiB SRAM and rp2350's 520 KiB cannot share
//! one figure). Those constants therefore have to be *pulled* from the active
//! platform — they cannot be injected at runtime. This module is the ONE place
//! the kernel reaches into `platform::chip` for them (the sanctioned
//! D-KERNEL-PLATFORM capacity seam); every other kernel site consumes the
//! constants from here, so the kernel↔platform capacity dependency is a single
//! audited surface rather than scattered reach-ins.
//!
//! On aarch64/wasm targets `platform::chip` re-exports the centralised
//! `abi::config::kernel` profile; on RP it re-exports the silicon-TOML values
//! generated by `build.rs` (per-silicon, which a single profile cannot express).

/// Bytes of the per-module state arena (must fit every loaded module's state).
pub const STATE_ARENA_SIZE: usize = crate::platform::chip::STATE_ARENA_SIZE;

/// Bytes of the shared buffer-pool arena.
pub const BUFFER_ARENA_SIZE: usize = crate::platform::chip::BUFFER_ARENA_SIZE;

/// Bytes reserved for the decoded boot configuration.
pub const CONFIG_ARENA_SIZE: usize = crate::platform::chip::CONFIG_ARENA_SIZE;

/// Maximum size of a single module's config-blob section.
pub const MAX_MODULE_CONFIG_SIZE: usize = crate::platform::chip::MAX_MODULE_CONFIG_SIZE;

/// Bytes of the Tier B elastic region and its grant quantum. Taken
/// from the arch profile directly rather than through
/// `platform::chip`: the values are profile-selected by target arch
/// and have no per-silicon TOML variation (MCU profiles pin the region
/// to 0 — elasticity compiles out).
pub const ELASTIC_REGION_SIZE: usize = crate::abi::config::kernel::ELASTIC_REGION_SIZE;
/// Grant granularity for [`ELASTIC_REGION_SIZE`] chunks.
pub const ELASTIC_QUANTUM: usize = crate::abi::config::kernel::ELASTIC_QUANTUM;
