//! Kernel syscall surfaces (minimal).

pub mod hal;
pub mod syscalls;
pub mod channel;
pub mod config;
pub mod scheduler;
pub mod loader;
pub mod net;
pub mod socket;
pub mod buffer_pool;
pub mod errno;
pub mod event;
#[cfg(feature = "rp")]
#[path = "../platform/rp_resource.rs"]
pub mod resource;
pub mod ringbuf;
pub mod fd;
pub mod provider;
#[cfg(feature = "rp")]
#[path = "../platform/rp_planner.rs"]
pub mod planner;
#[cfg(feature = "rp")]
#[path = "../platform/rp_flash_store.rs"]
pub mod flash_store;
#[cfg(feature = "rp")]
#[path = "../platform/rp_chip.rs"]
pub mod chip;
#[cfg(feature = "chip-bcm2712")]
#[path = "../platform/bcm2712_chip.rs"]
pub mod chip;
#[cfg(feature = "host-linux")]
#[path = "../platform/linux_chip.rs"]
pub mod chip;
#[cfg(feature = "rp")]
#[path = "../platform/rp_ext.rs"]
pub mod rp_ext;
pub mod guard;
pub mod heap;
pub mod step_guard;
pub mod bridge;
pub mod isr_tier;
#[cfg(feature = "chip-bcm2712")]
#[path = "../platform/bcm2712_cross_domain.rs"]
pub mod cross_domain;
#[path = "../platform/rp_mpu.rs"]
pub mod mpu;
#[cfg(feature = "chip-bcm2712")]
#[path = "../platform/bcm2712_mmu.rs"]
pub mod mmu;
#[cfg(feature = "chip-bcm2712")]
#[path = "../platform/bcm2712_pcie.rs"]
pub mod pcie;
#[cfg(feature = "chip-bcm2712")]
#[path = "../platform/bcm2712_smmu.rs"]
pub mod smmu;
#[cfg(feature = "chip-bcm2712")]
#[path = "../platform/bcm2712_nic_ring.rs"]
pub mod nic_ring;
pub mod page_pool;
#[path = "../platform/bcm2712_backing_store.rs"]
pub mod backing_store;
#[path = "../platform/bcm2712_pager.rs"]
pub mod pager;
#[cfg(feature = "rp")]
#[path = "../platform/rp_gpio.rs"]
pub mod gpio;
#[cfg(feature = "rp")]
#[path = "../platform/rp_pio_util.rs"]
pub mod pio_util;
