//! Kernel syscall surfaces (minimal).

pub mod syscalls;
pub mod channel;
pub mod config;
pub mod scheduler;
pub mod loader;
pub mod net;
pub mod socket;
pub mod buffer_pool;
pub mod errno;
pub mod event;
#[cfg(feature = "rp")]
pub mod resource;
pub mod ringbuf;
pub mod fd;
pub mod provider;
pub mod planner;
#[cfg(feature = "rp")]
pub mod flash_store;
pub mod chip;
pub mod guard;
pub mod heap;
pub mod step_guard;
pub mod bridge;
pub mod isr_tier;
#[cfg(feature = "chip-bcm2712")]
pub mod cross_domain;
pub mod mpu;
#[cfg(feature = "chip-bcm2712")]
pub mod mmu;
#[cfg(feature = "chip-bcm2712")]
pub mod pcie;
#[cfg(feature = "chip-bcm2712")]
pub mod smmu;
#[cfg(feature = "chip-bcm2712")]
pub mod nic_ring;
