version = "1.0.0"
hardware_targets = ["rp2350", "bcm2712"]

[[ports]]
name = "blocks"
direction = "input"
content_type = "OctetStream"
required = true

[[ports]]
name = "files"
direction = "output"
content_type = "OctetStream"
required = true

[[ports]]
name = "block_writes"
direction = "output"
content_type = "OctetStream"

[[ports]]
name = "seek"
direction = "ctrl_input"
content_type = "OctetStream"
