//! Build script for fluxor
//!
//! Provides the target-specific memory.x linker script and generates
//! chip_generated.rs from the silicon TOML [kernel] section.

use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};

use serde::Deserialize;

// ============================================================================
// TOML schema (only the [kernel] section)
// ============================================================================

#[derive(Deserialize)]
struct SiliconToml {
    kernel: Option<KernelConfig>,
}

#[derive(Deserialize)]
struct KernelConfig {
    watchdog_ctrl: String,
    boot2_src: String,
    state_arena_kb: u32,
    buffer_arena_kb: u32,
    config_buffer_kb: u32,
    config_arena_kb: u32,
    flash_erase_block_size: String,
    flash_erase_cmd: String,
    bootsel: BootselConfig,
}

#[derive(Deserialize)]
struct BootselConfig {
    dma_ch_count: u8,
    qspi_ss_bit: u8,
    flash_release_addr: String,
    flash_release_value: String,
    pad_addr: String,
    pad_value: String,
    ctrl_addr: String,
    ctrl_value: String,
    status_addr: String,
    gpio_hi_addr: String,
}

// ============================================================================
// Hex parsing
// ============================================================================

fn parse_hex(s: &str) -> u32 {
    let s = s.trim();
    if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u32::from_str_radix(hex, 16).expect(s)
    } else {
        s.parse::<u32>().expect(s)
    }
}

// ============================================================================
// Code generation
// ============================================================================

fn emit_const(gen: &mut String, name: &str, ty: &str, val: &str) {
    gen.push_str(&format!("pub const {name}: {ty} = {val};\n"));
}

fn emit_hex_const(gen: &mut String, name: &str, hex_str: &str) {
    let v = parse_hex(hex_str);
    gen.push_str(&format!("pub const {name}: u32 = {v:#010X};\n"));
}

fn generate_chip_rs(k: &KernelConfig, is_rp2040: bool) -> String {
    let mut g = String::from("// Auto-generated by build.rs from silicon TOML — do not edit\n\n");

    emit_hex_const(&mut g, "WATCHDOG_CTRL", &k.watchdog_ctrl);
    emit_hex_const(&mut g, "BOOT2_SRC", &k.boot2_src);
    g.push('\n');

    emit_const(
        &mut g,
        "STATE_ARENA_SIZE",
        "usize",
        &format!("{}", k.state_arena_kb * 1024),
    );
    emit_const(
        &mut g,
        "BUFFER_ARENA_SIZE",
        "usize",
        &format!("{}", k.buffer_arena_kb * 1024),
    );
    emit_const(
        &mut g,
        "MAX_MODULE_CONFIG_SIZE",
        "usize",
        &format!("{}", k.config_buffer_kb * 1024),
    );
    emit_const(
        &mut g,
        "CONFIG_ARENA_SIZE",
        "usize",
        &format!("{}", k.config_arena_kb * 1024),
    );
    g.push('\n');

    emit_hex_const(&mut g, "FLASH_ERASE_BLOCK_SIZE", &k.flash_erase_block_size);
    let cmd = parse_hex(&k.flash_erase_cmd) as u8;
    emit_const(&mut g, "FLASH_ERASE_CMD", "u8", &format!("{cmd:#04X}"));
    g.push('\n');

    let b = &k.bootsel;
    emit_const(
        &mut g,
        "BOOTSEL_DMA_CH_COUNT",
        "usize",
        &format!("{}", b.dma_ch_count),
    );
    emit_const(
        &mut g,
        "BOOTSEL_QSPI_SS_BIT",
        "u32",
        &format!("{}", b.qspi_ss_bit),
    );
    emit_hex_const(&mut g, "BOOTSEL_FLASH_RELEASE_ADDR", &b.flash_release_addr);
    emit_hex_const(
        &mut g,
        "BOOTSEL_FLASH_RELEASE_VALUE",
        &b.flash_release_value,
    );
    emit_hex_const(&mut g, "BOOTSEL_PAD_ADDR", &b.pad_addr);
    emit_hex_const(&mut g, "BOOTSEL_PAD_VALUE", &b.pad_value);
    emit_hex_const(&mut g, "BOOTSEL_CTRL_ADDR", &b.ctrl_addr);
    emit_hex_const(&mut g, "BOOTSEL_CTRL_VALUE", &b.ctrl_value);
    emit_hex_const(&mut g, "BOOTSEL_STATUS_ADDR", &b.status_addr);
    emit_hex_const(&mut g, "BOOTSEL_GPIO_HI_ADDR", &b.gpio_hi_addr);
    g.push('\n');

    emit_const(
        &mut g,
        "IS_RP2040",
        "bool",
        if is_rp2040 { "true" } else { "false" },
    );

    g
}

// ============================================================================
// Main
// ============================================================================

/// Exactly one supported target family per build invocation. Resolved from
/// cargo feature flags. Anything that doesn't match maps to a clear error so
/// silent fall-through (e.g. wasm builds picking up RP linker artifacts) can't
/// occur.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Platform {
    HostLinux,
    HostWasm,
    Bcm2712,
    Rp2040,
    Rp2350,
}

fn detect_platform() -> Platform {
    let rp2040 = env::var("CARGO_FEATURE_CHIP_RP2040").is_ok();
    let rp2350b = env::var("CARGO_FEATURE_CHIP_RP2350B").is_ok();
    let bcm = env::var("CARGO_FEATURE_CHIP_BCM2712").is_ok();
    let host_linux = env::var("CARGO_FEATURE_HOST_LINUX").is_ok();
    let host_wasm = env::var("CARGO_FEATURE_HOST_WASM").is_ok();

    let active: Vec<&str> = [
        ("chip-rp2040", rp2040),
        ("chip-rp2350b", rp2350b),
        ("chip-bcm2712", bcm),
        ("host-linux", host_linux),
        ("host-wasm", host_wasm),
    ]
    .iter()
    .filter_map(|(n, on)| if *on { Some(*n) } else { None })
    .collect();

    match active.as_slice() {
        ["chip-rp2040"] => Platform::Rp2040,
        ["chip-rp2350b"] => Platform::Rp2350,
        ["chip-bcm2712"] => Platform::Bcm2712,
        ["host-linux"] => Platform::HostLinux,
        ["host-wasm"] => Platform::HostWasm,
        // Zero active features means the workspace default kicked in.
        // The default in Cargo.toml is `chip-rp2350b`, but emitting a
        // deterministic error here is friendlier than a Cortex-M linker
        // arg surprising a host build.
        [] => panic!(
            "build.rs: no platform feature selected. Pass exactly one of \
             chip-rp2040 / chip-rp2350b / chip-bcm2712 / host-linux / host-wasm \
             with --no-default-features --features <name>. See `make targets`."
        ),
        _ => panic!(
            "build.rs: multiple conflicting platform features active: {:?}. \
             Pass exactly one.",
            active,
        ),
    }
}

fn main() {
    let out = &PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let platform = detect_platform();
    // Always emit the rerun guard so changing build.rs itself re-triggers.
    println!("cargo:rerun-if-changed=build.rs");
    // Re-run if any platform feature toggles, so a feature change forces
    // re-detection rather than picking up a stale artifact.
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_CHIP_RP2040");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_CHIP_RP2350B");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_CHIP_BCM2712");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_HOST_LINUX");
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_HOST_WASM");
    // Downstream Rust code can match on this cfg to assert platform identity
    // (e.g. a `#[cfg(fluxor_platform = "wasm")]` block that statically rejects
    // a stray RP-only `include!` ever reaching the wasm crate graph).
    let platform_str = match platform {
        Platform::HostLinux => "host-linux",
        Platform::HostWasm => "host-wasm",
        Platform::Bcm2712 => "bcm2712",
        Platform::Rp2040 => "rp2040",
        Platform::Rp2350 => "rp2350",
    };
    println!("cargo:rustc-check-cfg=cfg(fluxor_platform, values(\"host-linux\", \"host-wasm\", \"bcm2712\", \"rp2040\", \"rp2350\"))");
    println!("cargo:rustc-cfg=fluxor_platform=\"{platform_str}\"");

    match platform {
        Platform::HostLinux | Platform::HostWasm => {
            // Hosted targets: capacity tunables come from
            // `abi::config::kernel` (per-profile, selected at compile
            // time via `cfg(target_arch)` in `modules/sdk/config.rs`).
            // No linker script, no chip_generated.rs.
        }
        Platform::Bcm2712 => emit_bcm2712(out),
        Platform::Rp2040 => emit_rp(out, Rp::Rp2040),
        Platform::Rp2350 => emit_rp(out, Rp::Rp2350),
    }
}

fn emit_bcm2712(out: &Path) {
    // BCM2712 / CM5: single linker script with board-dependent RAM origin
    // via --defsym. Capacity constants come from the centralised
    // `abi::config::kernel::profile_host`; `targets/silicon/bcm2712.toml`
    // carries non-capacity metadata only.
    let is_cm5 = env::var("CARGO_FEATURE_BOARD_CM5").is_ok();
    let ram_origin = if is_cm5 { "0x80000" } else { "0x40080000" };
    File::create(out.join("memory-bcm2712.x"))
        .unwrap()
        .write_all(include_bytes!("memory-bcm2712.x"))
        .unwrap();
    println!("cargo:rustc-link-arg=-T{}/memory-bcm2712.x", out.display());
    println!("cargo:rustc-link-arg=--defsym=RAM_ORIGIN={}", ram_origin);
    println!("cargo:rerun-if-changed=memory-bcm2712.x");
    println!("cargo:rerun-if-changed=targets/silicon/bcm2712.toml");
}

enum Rp {
    Rp2040,
    Rp2350,
}

fn emit_rp(out: &Path, family: Rp) {
    let is_rp2040 = matches!(family, Rp::Rp2040);
    let linker_script = if is_rp2040 {
        include_bytes!("memory-rp2040.x") as &[u8]
    } else {
        include_bytes!("memory-rp2350.x") as &[u8]
    };
    File::create(out.join("memory.x"))
        .unwrap()
        .write_all(linker_script)
        .unwrap();

    let toml_path = if is_rp2040 {
        "targets/silicon/rp2040.toml"
    } else {
        "targets/silicon/rp2350a.toml"
    };
    let content =
        fs::read_to_string(toml_path).unwrap_or_else(|e| panic!("Failed to read {toml_path}: {e}"));
    let silicon: SiliconToml =
        toml::from_str(&content).unwrap_or_else(|e| panic!("Failed to parse {toml_path}: {e}"));
    let kernel = silicon
        .kernel
        .unwrap_or_else(|| panic!("{toml_path} missing [kernel] section"));

    let generated = generate_chip_rs(&kernel, is_rp2040);
    File::create(out.join("chip_generated.rs"))
        .unwrap()
        .write_all(generated.as_bytes())
        .unwrap();

    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=memory-rp2350.x");
    println!("cargo:rerun-if-changed=memory-rp2040.x");
    println!("cargo:rerun-if-changed=targets/silicon/rp2040.toml");
    println!("cargo:rerun-if-changed=targets/silicon/rp2350a.toml");
    println!("cargo:rerun-if-changed=targets/silicon/rp2350b.toml");
}
