version = "1.0.0"
hardware_targets = ["rp2350"]

[[ports]]
name = "net_in"
direction = "input"
content_type = "OctetStream"

[[ports]]
name = "g711"
index = 1
direction = "input"
content_type = "OctetStream"

[[ports]]
name = "net_out"
direction = "output"
content_type = "OctetStream"

[[ports]]
name = "packets"
index = 1
direction = "output"
content_type = "OctetStream"

[[ports]]
name = "endpoint"
direction = "ctrl_input"
content_type = "OctetStream"

[[resources]]
requires_contract = "channel"
access = "read"
