//! Per-silicon facts for the RP targets.
//!
//! Everything here is generated by build.rs from the silicon TOML, plus the
//! board TOML for the facts that belong to the board rather than the die.
//! There are no hand-written register accessors here: the variant
//! differences a hand-written layer would paper over — register positions,
//! peripheral counts, block bases — are declared as data and checked at
//! generation time instead.

// Generated constants from silicon TOML (RP targets only).
include!(concat!(env!("OUT_DIR"), "/chip_generated.rs"));

/// Whether PIO GPIOBASE register is available.
#[inline(always)]
pub const fn has_pio_gpiobase() -> bool {
    !IS_RP2040
}
