//! Project metadata files written into the registry on publish.
//!
//! Each canonical publish records a small TOML file at
//! `~/.fluxor/registry/projects/<name>/<version>.toml` capturing
//! the project's identity and `[dependencies]` at that release.
//! The lockfile resolver reads these files to walk transitive
//! dependencies.
//!
//! The format is a strict subset of `fluxor.toml`: just `[project]`
//! and `[dependencies]`. Other fields (`[ci]`, `[required]`, …) are
//! not relevant to dep resolution.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};
use crate::project::{self, DepSpec};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ProjectMeta {
    pub name: String,
    pub version: String,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub dependencies: BTreeMap<String, MetaDep>,
    /// Feature map mirrored from `fluxor.toml::[features]`.
    /// Transitive resolvers consult this so a downstream's
    /// active-feature set propagates through the dependency graph.
    /// The lockfile resolver records but does not yet activate
    /// transitive features — cargo-style unified-features is not
    /// implemented.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub features: BTreeMap<String, Vec<String>>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(untagged)]
pub enum MetaDep {
    Simple(String),
    Table(MetaDepTable),
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MetaDepTable {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
}

impl MetaDep {
    pub fn version_req(&self) -> Option<&str> {
        match self {
            MetaDep::Simple(v) => Some(v.as_str()),
            MetaDep::Table(t) => t.version.as_deref(),
        }
    }
}

pub fn meta_dir(registry_root: &Path) -> PathBuf {
    registry_root.join("projects")
}

pub fn meta_path(registry_root: &Path, name: &str, version: &str) -> PathBuf {
    meta_dir(registry_root)
        .join(name)
        .join(format!("{version}.toml"))
}

/// Build a `ProjectMeta` from the project's `fluxor.toml`. Only the
/// `[project]` and `[dependencies]` tables are read — everything
/// else stays project-local.
pub fn from_project_root(project_root: &Path) -> Result<ProjectMeta> {
    let identity = project::project_identity(project_root)
        .map_err(Error::Config)?
        .ok_or_else(|| {
            Error::Config(format!(
                "no [project] table in {}/fluxor.toml",
                project_root.display()
            ))
        })?;
    let deps = project::dependencies(project_root).map_err(Error::Config)?;
    let mut map: BTreeMap<String, MetaDep> = BTreeMap::new();
    for d in deps {
        map.insert(d.name.clone(), dep_spec_to_meta(&d));
    }
    let feats = project::features(project_root).map_err(Error::Config)?;
    Ok(ProjectMeta {
        name: identity.name,
        version: identity.version,
        dependencies: map,
        features: feats,
    })
}

fn dep_spec_to_meta(spec: &DepSpec) -> MetaDep {
    // Emit the simple string form when only a version is set, so
    // the on-disk file stays human-readable.
    if let DepSpec {
        version: Some(v),
        path: None,
        git: None,
        optional: false,
        ..
    } = spec
    {
        return MetaDep::Simple(v.clone());
    }
    MetaDep::Table(MetaDepTable {
        version: spec.version.clone(),
        path: spec.path.as_ref().map(|p| p.display().to_string()),
        git: spec.git.clone(),
        optional: if spec.optional { Some(true) } else { None },
    })
}

/// Write the meta file. Idempotent on identical content — re-publishes
/// of the same project version overwrite cleanly.
pub fn write_meta(registry_root: &Path, meta: &ProjectMeta) -> Result<PathBuf> {
    let path = meta_path(registry_root, &meta.name, &meta.version);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let body = toml::to_string_pretty(meta)
        .map_err(|e| Error::Config(format!("serialise project meta: {e}")))?;
    let header = format!(
        "# Generated by `fluxor publish` — project metadata for {} v{}\n\n",
        meta.name, meta.version
    );
    fs::write(&path, format!("{header}{body}"))?;
    Ok(path)
}

/// Read the meta file for a specific `(name, version)`. Returns
/// `Ok(None)` when absent — the caller usually treats that as "no
/// transitive deps to walk" rather than an error.
pub fn read_meta(registry_root: &Path, name: &str, version: &str) -> Result<Option<ProjectMeta>> {
    let path = meta_path(registry_root, name, version);
    if !path.exists() {
        return Ok(None);
    }
    let text = fs::read_to_string(&path)
        .map_err(|e| Error::Config(format!("read {}: {e}", path.display())))?;
    let parsed: ProjectMeta = toml::from_str(&text)
        .map_err(|e| Error::Config(format!("parse {}: {e}", path.display())))?;
    Ok(Some(parsed))
}
