version = "2.0.0"
hardware_targets = ["rp2350", "bcm2712"]

[[ports]]
name = "net_in"
direction = "input"
content_type = "OctetStream"

[[ports]]
name = "variables"
index = 1
direction = "input"
content_type = "FmpMessage"

[[ports]]
name = "file_data"
index = 2
direction = "input"
content_type = "OctetStream"

[[ports]]
name = "net_out"
direction = "output"
content_type = "OctetStream"

[[ports]]
name = "file_ctrl"
index = 1
direction = "output"
content_type = "OctetStream"

[[resources]]
device_class = "channel"
access = "read"
