//! Board-local PCIe device aliases for BCM2712 (Pi 5).
//!
//! The alias table is the seam between board topology and a stable,
//! user-facing name. Drivers and user YAML configs reference these
//! names (`m2_primary`, `rp1`); the `pcie_device` contract's binder
//! resolves them by matching the expected PCI (bus, dev, func) on a
//! named root complex. Scan order does not affect which device an
//! alias binds — a bridge or a reorder changes the enumeration index
//! but not the BDF.
//!
//! The alias entries are a **board fact**, not a source constant: they are
//! declared in the board TOML's `[platform.pcie]` section and generated into
//! `ALIASES` by `build.rs`. Pi 5 declares `m2_primary` (PCIe1, external x1 —
//! NVMe HAT+/M.2) and `rp1` (PCIe2, internal x4 → RP1); QEMU virt declares
//! none. Only PCIe1 is brought up by the bare-metal kernel; binding to `rp1`
//! returns ENODEV.
//!
//! An entry names the endpoint directly on bus 1 of its root. A card that
//! interposes a PCIe switch (endpoint on bus 2+) needs an updated BDF in the
//! board TOML or a deeper-walking binder — the alias explicitly fails to bind
//! rather than silently picking whichever device enumerates first.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PcieRoot {
    /// External x1 slot (NVMe HAT+).
    Pcie1,
    /// Internal x4 link to RP1.
    Pcie2,
}

pub struct PcieAlias {
    pub name: &'static str,
    pub root: PcieRoot,
    /// Expected PCI (bus, dev, func) of the device on `root`. The
    /// binder scans the enumeration table for a device with this
    /// exact triple; stable across enumeration reorders.
    pub bus: u8,
    pub dev: u8,
    pub func: u8,
}

// The alias table itself is board topology, generated by `build.rs` from the
// active board TOML's `[platform.pcie]` section (Pi 5 declares the NVMe/RP1
// devices; QEMU virt declares none → empty). Not a source-editable const.
include!(concat!(env!("OUT_DIR"), "/board_pcie_aliases.rs"));

/// Look up an alias by name. Case-sensitive — aliases are
/// ASCII-lowercase identifiers.
pub fn resolve(name: &str) -> Option<&'static PcieAlias> {
    ALIASES.iter().find(|a| a.name == name)
}

/// PCI class name → class code (bits 23:0 of the 32-bit class
/// register; low byte is PI, middle byte is subclass, high byte is
/// base class).
///
/// Only well-defined classes we bind drivers to are listed; unknown
/// names return `None` so `@class=…` selectors surface as configuration
/// errors rather than silently matching nothing.
pub fn class_code(name: &str) -> Option<u32> {
    match name {
        "nvme" => Some(0x01_08_02),     // storage / NVM / NVMe
        "ethernet" => Some(0x02_00_00), // network / ethernet
        _ => None,
    }
}
