version = "1.0.0"
hardware_targets = ["rp2350"]
permissions = ["platform_raw"]

[[ports]]
name = "pixels"
direction = "input"
content_type = "ImageRaw"
required = false

[[resources]]
requires_contract = "gpio"
access = "write"

[[resources]]
requires_contract = "pio"
access = "exclusive"

[[resources]]
requires_contract = "timer"
access = "write"

[[resources]]
requires_contract = "platform_dma_fd"
access = "exclusive"
